[request]
member_id = "b86326dbd7ec"
name = "bob"
public_key = """
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAnlnxAwOStE1XOROpc6brSE0Iu6Tg0D3bxyVg6vWwZjU=
-----END PUBLIC KEY-----

"""
keypackage = """
eyJpZGVudGl0eSI6IlltOWkiLCJzaWdfcHViIjoiV1Q5RVZVeHNvdnFITDB4OTNwL09xSnMyVUsyR1FOakJGSjFkN2FSK0ticz0iLCJpbml0X3B1YiI6IlI2K2FyQS8xTk9CbERjQmFOUElKd28xYTFMK0NtcUxLNnFyMkJwOXZwU0E9In0=
"""
timestamp = 1772115204
